### ISSUE TITLE
Django Admin issue: Current page not visible in Paginator

### ISSUE THREAD

**Issue by gijs** [lizardsystem/lizard-efcis#54]
Front-end problem in the back-end... 
Overriding the Django Admin stylesheet with the following snippet will make the current page visible:

``` css
span.this-page {
   font-weight: bolder !important;
}
```

Double of https://github.com/nens/efcis-site/issues/149
